import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import MobileMenu from "@/components/Layout/MobileMenu";
import { AppProvider } from "@/context/AppContext";
import Footer from "@/components/Layout/Footer";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";
import CartSidebar from "@/components/Layout/CartSidebar";
import BottomMenu from "@/components/Layout/BottomMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <Providers>
            <Header />
            <MobileMenu />
              <Toaster />
            {children}
            <CartSidebar/>
            <BottomMenu />
            </Providers>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
